#### 错误分类
---

**可恢复错误（Recoverable Errors）**
可恢复错误是指程序遇到预期的异常情况，但仍有可能通过适当的操作继续执行或优雅地降级服务。这类错误通常用 Result 类型来处理，允许程序在遇到错误时返回有意义的信息，并决定如何响应。

**不可恢复错误（Unrecoverable Errors）**
不可恢复错误指程序遇到严重故障，无法继续执行或无法提供有意义的结果。这类错误通常通过 `panic!` 宏触发，导致程序立即停止执行，打印堆栈跟踪，并进行必要的资源清理（如 `Drop trait` 的实现）。`panic!` 主要用于表示编程错误（如无效的状态、未初始化的变量等），而非预期的运行时错误。

#### `Result` 类型

`Result` 是 Rust 标准库提供的枚举类型，用于表示操作的两种可能结果：成功或失败。其定义如下：
```
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
- `T` 是成功时返回的值的类型（通常称为“Ok”值）。
- `E` 是失败时返回的错误类型。

使用 Result 的函数或方法可以返回具体的错误信息（封装在 `Err` 枚举成员中），而不是仅仅返回一个布尔值或空值来表示失败。这样，调用者可以根据返回的 `Result` 值决定如何处理错误。

#### 错误传播

==Rust 通过 `?` 运算符实现了错误传播机制。==在返回 `Result` 的函数或方法中，`?` 可以将当前 `Result` 的 `Err` 值直接返回给调用者，而 Ok 值则会被解包并继续执行后续代码。这极大地简化了错误处理代码的编写：

```
fn read_file(path: &str) -> Result<String, io::Error> {
    let mut file = File::open(path)?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    Ok(contents)
}
```

#### 自定义错误类型

为了提供丰富的错误信息和更好的错误处理体验，通常会定义自定义错误类型。自定义错误类型通常实现 `std::error::Error trait`，以便与其他错误类型兼容，并提供有用的错误信息。可以使用 `thiserror` 或 `anyhow` 等 `crates` 来简化自定义错误类型的定义。
```
pub enum Error{  
    IO(std::io::Error)  
}  
  
impl From<std::io::Error> for Error{  
    fn from(value: std::io::Error) -> Self {  
        Error::IO(value)  
    }  
}
```
##### `unwrap` 和 `expect`
在开发或测试阶段，可以使用 Result 的 `unwrap` 或 `expect` 方法快速获取 Ok 值，同时在遇到 `Err` 时立即触发 `panic!`。这主要用于临时调试或对错误处理有绝对信心的代码片段，不应在生产环境中广泛使用：

```
let value = result.unwrap(); // 如果 result 是 Err，程序会 panic!
let value = result.expect("An informative message on failure"); // 同上，附带自定义消息
```

##### `Option` 与错误处理

虽然 Option 类型不是专门用于错误处理，但在很多情况下，它用于表示可能缺失的值，可以作为简单的错误处理机制。Option 提供了 `map`、`and_then`、`unwrap_or`、`unwrap_or_else` 等方法，便于在值存在时进行进一步处理，或在值不存在时提供默认值或触发备用逻辑


#### panic! 与异常处理

`panic! `宏触发程序的异常终止，打印堆栈跟踪，并清理相关资源。尽管它常用于表示不可恢复的编程错误，但在某些场景下也可用于临时的错误处理。然而，过度依赖 `panic!` 可能导致程序不够健壮，因此通常建议使用 `Result` 进行更精细的错误控制。